# Generated by Django 2.2 on 2023-01-30 21:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_ordering', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True, verbose_name='дата заказа')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('telephone', models.CharField(max_length=16, verbose_name='телефон')),
                ('email', models.EmailField(max_length=254)),
                ('city', models.CharField(max_length=255, verbose_name='город')),
                ('address', models.TextField(verbose_name='адрес')),
                ('payment_method', models.CharField(choices=[(1, 'Онлайн картой'), (2, 'Онлайн со случайного чужого счета')], default=1, max_length=1, verbose_name='способ оплаты')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='коментарий')),
                ('paid', models.NullBooleanField(default=None, verbose_name='оплачено')),
                ('error_message', models.TextField(blank=True, default=None, null=True, verbose_name='сообщение об ошибке')),
            ],
            options={
                'verbose_name': 'заказ',
                'verbose_name_plural': 'заказы',
            },
        ),
        migrations.AlterField(
            model_name='deliverymethod',
            name='free_delivery_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='стоимость заказа, после которой действует бесплатная доставка'),
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='цена')),
                ('quantity', models.PositiveIntegerField(verbose_name='количество')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='app_ordering.Order', verbose_name='заказ')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='app_catalog.Product', verbose_name='заказ')),
            ],
            options={
                'verbose_name': 'единица заказа',
                'verbose_name_plural': 'единицы заказа',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_method',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='app_ordering.DeliveryMethod', verbose_name='способ доставки'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='пользователь'),
        ),
    ]
