# Generated by Django 2.2 on 2023-01-31 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ordering', '0002_auto_20230130_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='итоговая стоимость'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_method',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='app_ordering.DeliveryMethod', verbose_name='способ доставки'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='error_message',
            field=models.TextField(blank=True, default='', null=True, verbose_name='сообщение об ошибке'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('1', 'Онлайн картой'), ('2', 'Онлайн со случайного чужого счета')], default=1, max_length=1, verbose_name='способ оплаты'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='app_catalog.Product', verbose_name='товар'),
        ),
    ]
