# Generated by Django 2.2 on 2023-02-11 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ordering', '0003_auto_20230131_1924'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_price',
            field=models.DecimalField(decimal_places=2, default=2, max_digits=10, verbose_name='стоимость доставки'),
            preserve_default=False,
        ),
    ]
