# Generated by Django 2.2 on 2022-10-04 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0002_auto_20220925_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='telephone',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='телефон'),
        ),
    ]
