# Generated by Django 2.2 on 2022-11-27 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0003_auto_20221004_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='telephone',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='телефон'),
        ),
    ]
