# Generated by Django 2.2 on 2022-12-27 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0004_auto_20221127_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='telephone',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='телефон'),
        ),
    ]
