# Generated by Django 2.2 on 2022-09-18 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='название')),
                ('sort_index', models.PositiveIntegerField(verbose_name='индекс сортировки')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='иконка')),
                ('active', models.BooleanField(default=False, verbose_name='активно')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categories', to='app_catalog.Category', verbose_name='родитель')),
            ],
            options={
                'verbose_name': 'категория',
                'verbose_name_plural': 'категории',
            },
        ),
    ]
