# Generated by Django 2.2 on 2022-11-03 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_catalog', '0005_auto_20221030_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='active',
            field=models.BooleanField(default=False, verbose_name='активно'),
        ),
    ]
