# Generated by Django 2.2 on 2022-11-08 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_catalog', '0007_auto_20221105_1959'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/categories/', verbose_name='изображение'),
        ),
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.FileField(blank=True, null=True, upload_to='images/icons/', verbose_name='иконка'),
        ),
    ]
